name: file operation in Github

on: workflow dispacth  # 👈 space compulsory

jobs:
  files:
    runs-on: ubuntu-latest

    steps:
      - name: create a one file
        run: echo "KK DEVOPS 12345" > devops.txt

      - name: display the content of the file
        run: cat devops.txt

      - name: display the date
        run: date

      - name: Display the file and dir
        run: ls -lrth