name: Upload and Download Artifact

on:
  push: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create file
      run: echo "Hello Vijay" > sample.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: sample.txt

    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
